[package]
name = "joins"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.70"
futures = "0.3.28"
reqwest = "0.11.16"
tokio = { version = "1", features = ["full"] }
